# 4 Final Processing

In [1]:
import pandas as pd

In [4]:
# show *all* rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# widen the “page” so it won’t wrap columns  
pd.set_option('display.width', 1000)

In [2]:
df_listings = pd.read_csv("./data/eustartup_listings_enriched_5.csv")

In [5]:
df_listings.head(3)

,name,link_startupeu,link_logo,website,city,region,tags,category,business_description,founded,age,total_funding,company_status,social_links,writing_score,clarity_score,innovativeness_score,market_readiness_score,founder_signal_score,sentiment_score,traction_score,word_count,sentence_count,jargon_density,numeric_evidence_count,call_to_action_flag,top_3_keywords,business_model,website_valid,website_clean,website_up,website_response_ms,redirected_url,name_cleaned,Startup,Instagram,X,LinkedIn,General,general_root,website_host,general_host,Headlines,n_valid_headlines,valid_headlines,validation_reasons,startup,success_count,total_funding_eur,acquisition_count,bankruptcy_count,non_success_count,linkedin_global_profile,linkedin_handle,instagram_handle,x_handle,reason_instagram,reason_linkedin,reason_x,valid_instagram,valid_linkedin,valid_x
0,Avdain,https://www.eu-startups.com/directory/avdain/,https://www.eu-startups.com/wp-content/uploads...,avdain.com,Vienna,Vienna,"company, startup, one person",Software & Analytics,Avdain is a enterprise that embodies a fusion ...,2020,5,No funding announced yet,Active,(),8,7,9.0,6,8,9,5,290,12,0.25,0,0,"['innovation', 'academic', 'entrepreneurial']",B2B,True,https://avdain.com,True,131.8,NaN,Avdain,Avdain,NaN,NaN,NaN,https://www.avdain.com/our-mission,https://avdain.com,avdain.com,avdain.com,[],0,[],NaN,Avdain,0,0,0,0,0,False,NaN,NaN,NaN,"Empty handle, does not represent an account.","Empty handle, does not represent an account.","Empty handle, does not represent an account.",False,False,False
1,Popper Power GmbH,https://www.eu-startups.com/directory/popper-p...,https://www.eu-startups.com/wp-content/uploads...,www.popperpower.com,Vienna,Vienna,"ev, battery, bess, charging",Energy,Popper Power GmbH develops advanced energy sto...,2022,3,Between €500K-€ 1 million,Active,"('https://www.linkedin.com/company/86313916',)",7,8,9.0,6,7,8,5,42,2,0.21,0,0,"['energy storage', 'EV charging', 'infrastruct...",B2B,True,https://popperpower.com,True,262.3,NaN,Popper Power,Popper Power,https://www.instagram.com/popperpower/,NaN,https://at.linkedin.com/company/popperpower,https://www.popperpower.com/?srsltid=AfmBOoqrk...,https://popperpower.com,popperpower.com,popperpower.com,"[{'title': 'Insolvenz | Popper Power GmbH', 'l...",4,"['Insolvenz | Popper Power GmbH', 'Insolvenz |...","['Reports a risk event (insolvency).', 'Report...",Popper Power,0,0,0,4,0,False,popperpower,popperpower,NaN,"The handle matches the startup's name exactly,...","The handle matches the startup's name exactly,...","The handle is missing, which cannot represent ...",True,True,False
2,Setter AI,https://www.eu-startups.com/directory/setter-ai/,https://www.eu-startups.com/wp-content/uploads...,https://www.trysetter.com,Wien,Vienna,"ai, ai agents, sales & marketing, ai saas, ai ...",Software & Analytics,Speed matters when you want more sales. That’s...,2024,1,Between €1-€100K,Active,(),8,9,7.0,8,6,9,7,305,15,0.20,2,1,"['sales', 'AI', 'integration']",B2B,True,https://trysetter.com,True,215.9,NaN,Setter AI,Setter AI,https://www.instagram.com/trysetter/,https://x.com/trysetter,NaN,https://www.trysetter.com/,https://trysetter.com,trysetter.com,trysetter.com,[{'title': 'Amazon-sjefen i Storbritannia sett...,0,[],NaN,Setter AI,0,0,0,0,0,False,NaN,trysetter,trysetter,"The handle 'trysetter' is short and relevant, ...",The handle is missing.,"Similar to Instagram, 'trysetter' is a suitabl...",True,False,True

In [3]:
for col in df_listings.columns:
    print(col)

name
link_startupeu
link_logo
website
city
region
tags
category
business_description
founded
age
total_funding
company_status
social_links
writing_score
clarity_score
innovativeness_score
market_readiness_score
founder_signal_score
sentiment_score
traction_score
word_count
sentence_count
jargon_density
numeric_evidence_count
call_to_action_flag
top_3_keywords
business_model
website_valid
website_clean
website_up
website_response_ms
redirected_url
name_cleaned
Startup
Instagram
X
LinkedIn
General
general_root
website_host
general_host
Headlines
n_valid_headlines
valid_headlines
validation_reasons
startup
success_count
total_funding_eur
acquisition_count
bankruptcy_count
non_success_count
linkedin_global_profile
linkedin_handle
instagram_handle
x_handle
reason_instagram
reason_linkedin
reason_x
valid_instagram
valid_linkedin
valid_x

In [6]:
# 1) Define the columns you want to keep
keep_cols = [
    "name_cleaned",
    "link_startupeu",
    "link_logo",
    "website_host",
    "website_up",
    "city",
    "region",
    "category",
    "top_3_keywords",
    "business_model",
    "linkedin_global_profile",
    "linkedin_handle",
    "valid_linkedin",
    "instagram_handle",
    "valid_instagram",
    "x_handle",
    "valid_x",
    "founded",
    "age",
    "total_funding",
    "n_valid_headlines",
    "valid_headlines",
    "success_count",
    "total_funding_eur",
    "acquisition_count",
    "bankruptcy_count",
    "non_success_count",
    "writing_score",
    "clarity_score",
    "innovativeness_score",
    "market_readiness_score",
    "founder_signal_score",
    "sentiment_score",
    "traction_score",
    "word_count",
    "sentence_count",
    "jargon_density",
    "numeric_evidence_count",
    "call_to_action_flag"
]

# 2) Subset your DataFrame
df_small = df_listings[keep_cols].copy()

# 3) Define the rename mapping
rename_map = {
    "name_cleaned": "name",
    "website_host": "link_website",
    "valid_linkedin": "linkedin_valid",
    "valid_instagram": "instagram_valid",
    "valid_x": "x_valid",
    "founded": "founded_year",
    "total_funding": "total_funding_listing",
    "n_valid_headlines": "headline_count",
    "valid_headlines": "headlines",
    "success_count": "headline_financial_count",
    "total_funding_eur": "headline_funding",
    "acquisition_count": "headline_acquisition_count",
    "bankruptcy_count": "headline_bankruptcy_count",
    "non_success_count": "headline_non_financial_count"
}

# 4) Apply the renaming
df_small.rename(columns=rename_map, inplace=True)

# 5) Inspect the result
print(df_small.columns.tolist())
df_small.head()

['name', 'link_startupeu', 'link_logo', 'link_website', 'website_up', 'city', 'region', 'category', 'top_3_keywords', 'business_model', 'linkedin_global_profile', 'linkedin_handle', 'linkedin_valid', 'instagram_handle', 'instagram_valid', 'x_handle', 'x_valid', 'founded_year', 'age', 'total_funding_listing', 'headline_count', 'headlines', 'headline_financial_count', 'headline_funding', 'headline_acquisition_count', 'headline_bankruptcy_count', 'headline_non_financial_count', 'writing_score', 'clarity_score', 'innovativeness_score', 'market_readiness_score', 'founder_signal_score', 'sentiment_score', 'traction_score', 'word_count', 'sentence_count', 'jargon_density', 'numeric_evidence_count', 'call_to_action_flag']

           name                                     link_startupeu                                          link_logo      link_website  website_up    city  region              category                                     top_3_keywords business_model  linkedin_global_profile linkedin_handle  linkedin_valid instagram_handle  instagram_valid      x_handle  x_valid  founded_year  age      total_funding_listing  headline_count                                          headlines  headline_financial_count  headline_funding  headline_acquisition_count  headline_bankruptcy_count  headline_non_financial_count  writing_score  clarity_score  innovativeness_score  market_readiness_score  founder_signal_score  sentiment_score  traction_score  word_count  sentence_count  jargon_density  numeric_evidence_count  call_to_action_flag
0        Avdain      https://www.eu-startups.com/directory/avdain/  https://www.eu-startups.com/wp-content/uploads...        avdain.com        True  Vienna  Vienna  Software & Analytics      ['innovation', 'academic', 'entrepreneurial']            B2B                    False             NaN           False              NaN            False           NaN    False          2020    5   No funding announced yet               0                                                 []                         0                 0                           0                          0                             0              8              7                   9.0                       6                     8                9               5         290              12            0.25                       0                    0
1  Popper Power  https://www.eu-startups.com/directory/popper-p...  https://www.eu-startups.com/wp-content/uploads...   popperpower.com        True  Vienna  Vienna                Energy  ['energy storage', 'EV charging', 'infrastruct...            B2B                    False     popperpower            True      popperpower             True           NaN    False          2022    3  Between €500K-€ 1 million               4  ['Insolvenz | Popper Power GmbH', 'Insolvenz |...                         0                 0                           0                          4                             0              7              8                   9.0                       6                     7                8               5          42               2            0.21                       0                    0
2     Setter AI   https://www.eu-startups.com/directory/setter-ai/  https://www.eu-startups.com/wp-content/uploads...     trysetter.com        True    Wien  Vienna  Software & Analytics                     ['sales', 'AI', 'integration']            B2B                    False             NaN           False        trysetter             True     trysetter     True          2024    1           Between €1-€100K               0                                                 []                         0                 0                           0                          0                             0              8              9                   7.0                       8                     6                9               7         305              15            0.20                       2                    1
3  SurveySensum  https://www.eu-startups.com/directory/surveyse...  https://www.eu-startups.com/wp-content/uploads...  surveysensum.com        True  vienna  Vienna  Software & Analytics      ['customer feedback', 'CX', 'business goals']            B2B                     True    surveysensum            True     surveysensum             True  surveysensum     True          2018    7   No funding announced yet               0                                                 []                         0                 0                           0                          0                             0              8              9                   7.0                       8                     6                9               7         203              10            0.20                       0                    0
4        Artypa      https://www.eu-startups.com/directory/artypa/  https://www.eu-startups.com/wp-content/uploads...        artypa.com        True  Vienna  Vienna  Software & Analytics                   ['AI', 'platform', 'efficiency']            B2B                    False             NaN           False           artypa             True           NaN    False          2024    1   No funding announced yet               0                                                 []                         0                 0                           0                          0                             0              8              9                   7.0                       6                     5                8               4         335              15            0.20                       0                    0

**Remove Invalid Handles**

In [8]:
# For any handle where the corresponding “_valid” flag is False, set that handle to NaN
df_small.loc[~df_small["linkedin_valid"], "linkedin_handle"]   = pd.NA
df_small.loc[~df_small["instagram_valid"], "instagram_handle"] = pd.NA
df_small.loc[~df_small["x_valid"], "x_handle"]                 = pd.NA

# (Optional) inspect a few rows to confirm
print(df_small[[
    "name",
    "linkedin_handle", "linkedin_valid",
    "instagram_handle", "instagram_valid",
    "x_handle",       "x_valid"
]].head())

           name linkedin_handle  linkedin_valid instagram_handle  instagram_valid      x_handle  x_valid
0        Avdain            <NA>           False             <NA>            False          <NA>    False
1  Popper Power     popperpower            True      popperpower             True          <NA>    False
2     Setter AI            <NA>           False        trysetter             True     trysetter     True
3  SurveySensum    surveysensum            True     surveysensum             True  surveysensum     True
4        Artypa            <NA>           False           artypa             True          <NA>    False

**Remove down websites**

In [9]:
# Set link_website to NaN wherever website_up is False
df_small.loc[~df_small["website_up"], "link_website"] = pd.NA

# Optional: verify the change
print(df_small[["name", "link_website", "website_up"]].head())

           name      link_website  website_up
0        Avdain        avdain.com        True
1  Popper Power   popperpower.com        True
2     Setter AI     trysetter.com        True
3  SurveySensum  surveysensum.com        True
4        Artypa        artypa.com        True

**Remove duplicates**

In [11]:
import pandas as pd

# 1) Build a mask of rows to drop: any duplicate non-null handle in x, instagram, or linkedin
mask_dup = pd.Series(False, index=df_small.index)
for col in ["x_handle", "instagram_handle", "linkedin_handle"]:
    dup = df_small[col].duplicated(keep="first") & df_small[col].notna()
    mask_dup |= dup

# 2) Drop those rows, keep only the first occurrence per handle
df_small = df_small.loc[~mask_dup].reset_index(drop=True)

# 3) (Optional) Inspect how many were removed
print(f"Dropped {mask_dup.sum()} rows with duplicate handles.")

# 4) Verify no duplicates remain
for col in ["x_handle", "instagram_handle", "linkedin_handle"]:
    print(f"Remaining unique {col}: {df_small[col].nunique(dropna=True)}")

Dropped 5 rows with duplicate handles.
Remaining unique x_handle: 187
Remaining unique instagram_handle: 308
Remaining unique linkedin_handle: 361

           name                                     link_startupeu                                          link_logo      link_website  website_up    city  region              category                                     top_3_keywords business_model  linkedin_global_profile linkedin_handle  linkedin_valid instagram_handle  instagram_valid      x_handle  x_valid  founded_year  age      total_funding_listing  headline_count                                          headlines  headline_financial_count  headline_funding  headline_acquisition_count  headline_bankruptcy_count  headline_non_financial_count  writing_score  clarity_score  innovativeness_score  market_readiness_score  founder_signal_score  sentiment_score  traction_score  word_count  sentence_count  jargon_density  numeric_evidence_count  call_to_action_flag
0        Avdain      https://www.eu-startups.com/directory/avdain/  https://www.eu-startups.com/wp-content/uploads...        avdain.com        True  Vienna  Vienna  Software & Analytics      ['innovation', 'academic', 'entrepreneurial']            B2B                    False            <NA>           False             <NA>            False          <NA>    False          2020    5   No funding announced yet               0                                                 []                         0                 0                           0                          0                             0              8              7                   9.0                       6                     8                9               5         290              12            0.25                       0                    0
1  Popper Power  https://www.eu-startups.com/directory/popper-p...  https://www.eu-startups.com/wp-content/uploads...   popperpower.com        True  Vienna  Vienna                Energy  ['energy storage', 'EV charging', 'infrastruct...            B2B                    False     popperpower            True      popperpower             True          <NA>    False          2022    3  Between €500K-€ 1 million               4  ['Insolvenz | Popper Power GmbH', 'Insolvenz |...                         0                 0                           0                          4                             0              7              8                   9.0                       6                     7                8               5          42               2            0.21                       0                    0
2     Setter AI   https://www.eu-startups.com/directory/setter-ai/  https://www.eu-startups.com/wp-content/uploads...     trysetter.com        True    Wien  Vienna  Software & Analytics                     ['sales', 'AI', 'integration']            B2B                    False            <NA>           False        trysetter             True     trysetter     True          2024    1           Between €1-€100K               0                                                 []                         0                 0                           0                          0                             0              8              9                   7.0                       8                     6                9               7         305              15            0.20                       2                    1
3  SurveySensum  https://www.eu-startups.com/directory/surveyse...  https://www.eu-startups.com/wp-content/uploads...  surveysensum.com        True  vienna  Vienna  Software & Analytics      ['customer feedback', 'CX', 'business goals']            B2B                     True    surveysensum            True     surveysensum             True  surveysensum     True          2018    7   No funding announced yet               0                                                 []                         0                 0                           0                          0                             0              8              9                   7.0                       8                     6                9               7         203              10            0.20                       0                    0
4        Artypa      https://www.eu-startups.com/directory/artypa/  https://www.eu-startups.com/wp-content/uploads...        artypa.com        True  Vienna  Vienna  Software & Analytics                   ['AI', 'platform', 'efficiency']            B2B                    False            <NA>           False           artypa             True          <NA>    False          2024    1   No funding announced yet               0                                                 []                         0                 0                           0                          0                             0              8              9                   7.0                       6                     5                8               4         335              15            0.20                       0                    0

In [12]:
import pandas as pd

# 1) Identify duplicate link_website values (excluding NaN), keeping only the first occurrence
dup_web = df_small["link_website"].duplicated(keep="first") & df_small["link_website"].notna()

# 2) Drop those duplicate rows
df_small = df_small.loc[~dup_web].reset_index(drop=True)

# 3) (Optional) Inspect how many were removed
print(f"Dropped {dup_web.sum()} rows with duplicate link_website.")

# 4) Verify no duplicates remain
print(f"Remaining unique link_website: {df_small['link_website'].nunique(dropna=True)}")

Dropped 1 rows with duplicate link_website.
Remaining unique link_website: 436

**Check Top 10 values**

In [13]:
top10_data = {}

for col in df_small.columns:
    # include NaNs, then take the top 10
    vc = df_small[col] \
         .value_counts(dropna=False) \
         .head(10)

    # (optional) relabel the NaN index to "<Missing>"
    vc.index = vc.index.where(~vc.index.isna(), '<Missing>')

    top_values = vc.index.tolist()
    top_counts = vc.values.tolist()

    top10_data[col]       = pd.Series(top_values)
    top10_data[f"{col}_count"] = pd.Series(top_counts)

top10_df = pd.DataFrame(top10_data)

display(top10_df)

,name,name_count,link_startupeu,link_startupeu_count,link_logo,link_logo_count,link_website,link_website_count,website_up,website_up_count,city,city_count,region,region_count,category,category_count,top_3_keywords,top_3_keywords_count,business_model,business_model_count,linkedin_global_profile,linkedin_global_profile_count,linkedin_handle,linkedin_handle_count,linkedin_valid,linkedin_valid_count,instagram_handle,instagram_handle_count,instagram_valid,instagram_valid_count,x_handle,x_handle_count,x_valid,x_valid_count,founded_year,founded_year_count,age,age_count,total_funding_listing,total_funding_listing_count,headline_count,headline_count_count,headlines,headlines_count,headline_financial_count,headline_financial_count_count,headline_funding,headline_funding_count,headline_acquisition_count,headline_acquisition_count_count,headline_bankruptcy_count,headline_bankruptcy_count_count,headline_non_financial_count,headline_non_financial_count_count,writing_score,writing_score_count,clarity_score,clarity_score_count,innovativeness_score,innovativeness_score_count,market_readiness_score,market_readiness_score_count,founder_signal_score,founder_signal_score_count,sentiment_score,sentiment_score_count,traction_score,traction_score_count,word_count,word_count_count,sentence_count,sentence_count_count,jargon_density,jargon_density_count,numeric_evidence_count,numeric_evidence_count_count,call_to_action_flag,call_to_action_flag_count
0,Vira Therapeutics,1,https://www.eu-startups.com/directory/vira-the...,1,https://www.eu-startups.com/wp-content/uploads...,1,<Missing>,73,True,436.0,Vienna,294,Vienna,311.0,Software & Analytics,255,"['Machine Learning', 'retail', 'demand forecas...",2,B2B,318.0,False,487.0,<Missing>,148,True,361.0,<Missing>,202,True,307.0,<Missing>,322,False,322.0,2020,122,5,122,No funding announced yet,300.0,0,173,[],173,0,286,0,387,0.0,471.0,0.0,486.0,0.0,287.0,7.0,314.0,8.0,288.0,<Missing>,121.0,6.0,216.0,5.0,212.0,8.0,276.0,4.0,284.0,56,45,5,99,0.25,214,0.0,400.0,0.0,431.0
1,Avdain,1,https://www.eu-startups.com/directory/avdain/,1,https://www.eu-startups.com/wp-content/uploads...,1,permar.ai,1,False,73.0,Linz,41,Upper Austria,66.0,Health,53,"['sales', 'AI', 'integration']",1,B2C,135.0,True,22.0,popperpower,1,False,148.0,moneycare.io,1,False,202.0,trysetter,1,True,187.0,2019,115,6,115,Between €100K-€500K,62.0,1,89,"['Insolvenz | Popper Power GmbH', 'Insolvenz |...",1,1,53,1000000,13,1.0,26.0,1.0,10.0,1.0,99.0,8.0,129.0,9.0,98.0,7.0,115.0,5.0,159.0,6.0,148.0,7.0,148.0,5.0,109.0,66,44,4,85,0.20,109,1.0,84.0,1.0,78.0
2,Popper Power,1,https://www.eu-startups.com/directory/popper-p...,1,https://www.eu-startups.com/wp-content/uploads...,1,evologic-technologies.com,1,NaN,NaN,Graz,39,Styria,48.0,Professional Services,53,"['customer feedback', 'CX', 'business goals']",1,B2B2C,22.0,NaN,NaN,surveysensum,1,NaN,NaN,leftshift_one,1,NaN,NaN,surveysensum,1,NaN,NaN,2021,84,4,84,Between €1 million-€ 2.5 million,44.0,2,61,"['KEBA Group übernimmt KI-Vorreiter 7LYTIX', '...",1,3,46,100000,8,2.0,6.0,2.0,9.0,2.0,49.0,6.0,54.0,7.0,69.0,6.0,96.0,7.0,66.0,7.0,80.0,6.0,43.0,3.0,58.0,104,35,3,83,0.15,36,2.0,16.0,NaN,NaN
3,Setter AI,1,https://www.eu-startups.com/directory/setter-ai/,1,https://www.eu-startups.com/wp-content/uploads...,1,fretello.com,1,NaN,NaN,Innsbruck,13,Lower Austria,29.0,FinTech/InsurTech,29,"['AI', 'platform', 'efficiency']",1,platform,20.0,NaN,NaN,506-ai,1,NaN,NaN,vr_innerspace,1,NaN,NaN,wedding_capsule,1,NaN,NaN,2022,52,3,52,Between €500K-€ 1 million,27.0,3,47,"['Goodbye, Wisr: Wiener HR-Startup für ältere ...",1,5,43,600000,8,5.0,3.0,5.0,2.0,3.0,40.0,5.0,9.0,6.0,43.0,8.0,93.0,4.0,31.0,4.0,41.0,9.0,39.0,7.0,19.0,83,24,6,65,0.10,29,3.0,6.0,NaN,NaN
4,SurveySensum,1,https://www.eu-startups.com/directory/surveyse...,1,https://www.eu-startups.com/wp-content/uploads...,1,podpally.com,1,NaN,NaN,Salzburg,9,Tyrol,24.0,Media & Entertainment,17,"['podcast', 'research', 'prep']",1,marketplace,11.0,NaN,NaN,daiki-ai,1,NaN,NaN,trysetter,1,NaN,NaN,506ai_,1,NaN,NaN,2023,37,2,37,Between €1-€100K,24.0,4,30,['Silentium Tech receives regulatory approval ...,1,2,38,500000,6,3.0,2.0,4.0,1.0,4.0,16.0,9.0,2.0,5.0,8.0,9.0,54.0,8.0,26.0,8.0,16.0,5.0,3.0,2.0,18.0,85,22,1,38,0.14,26,4.0,2.0,NaN,NaN
5,Artypa,1,https://www.eu-startups.com/directory/artypa/,1,https://www.eu-startups.com/wp-content/uploads...,1,viratherapeutics.com,1,NaN,NaN,Wien,8,Salzburg,13.0,AgTech/FoodTech,15,"['guestbook', 'memories', 'wedding']",1,other,3.0,NaN,NaN,wasitai,1,NaN,NaN,oktavcom,1,NaN,NaN,finslice_eu,1,NaN,NaN,2018,30,7,30,Between €2.5 million-5 million,24.0,5,27,['Boomerank: NÖ E-Commerce-Assistent Startup e...,1,4,26,6000000,5,4.0,1.0,3.0,1.0,5.0,9.0,4.0,1.0,4.0,3.0,5.0,30.0,3.0,9.0,3.0,7.0,NaN,NaN,6.0,13.0,42,22,2,31,0.00,15,5.0,1.0,NaN,NaN
6,Podpally,1,https://www.eu-startups.com/directory/podpally/,1,https://www.eu-startups.com/wp-content/uploads...,1,artypa.com,1,NaN,NaN,Klagenfurt,4,Vorarlberg,7.0,Mobility,13,"['training plans', 'Hyrox', 'athletes']",1,NaN,NaN,NaN,NaN,dignaai,1,NaN,NaN,monkee_rocks,1,NaN,NaN,wasitai_,1,NaN,NaN,2017,23,8,23,Above €25 million,14.0,7,24,['Wiener Agentur Startaparat expandiert nach D...,1,6,11,2200000,4,NaN,NaN,NaN,NaN,6.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,9.0,4.0,NaN,NaN,8.0,4.0,134,20,7,30,0.50,12,NaN,NaN,NaN,NaN
7,Wedding Capsule,1,https://www.eu-startups.com/directory/wedding-...,1,https://www.eu-startups.com/wp-content/uploads...,1,helloagain.at,1,NaN,NaN,Klosterneuburg,3,Carinthia,7.0,Education,12,"['AI', 'automation', 'enterprise']",1,NaN,NaN,NaN,NaN,idcanopy,1,NaN,NaN,ilvi_official,1,NaN,NaN,cimphonyai,1,NaN,NaN,2024,17,1,17,Between €5 million-€10 million,12.0,6,23,['dinster.at'],1,7,4,2500000,4,NaN,NaN,NaN,NaN,7.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,NaN,9.0,3.0,108,19,10,23,0.30,8,NaN,NaN,NaN,NaN
8,Hyrox Training Plans,1,https://www.eu-startups.com/directory/hyrox-tr...,1,https://www.eu-startups.com/wp-content/uploads...,1,testify.io,1,NaN,NaN,Niederosterreich,3,Burgenland,4.0,Hardware,12,"['teachers', 'worksheets', 'customize']",1,NaN,NaN,NaN,NaN,wemeglobal,1,NaN,NaN,velonto,1,NaN,NaN,digna_can,1,NaN,NaN,2015,15,10,15,Between €10 million-€25 million,2.0,8,19,['25-Millionen-Dollar-Investment für Wiener St...,1,8,1,2000000,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,92,17,8,23,0.40,8,NaN,NaN,NaN,NaN
9,506.ai,1,https://www.eu-startups.com/directory/506ai/,1,https://www.eu-startups.com/wp-content/uploads...,1,allcyte.com,1,NaN,NaN,Wels,3,NaN,NaN,e-commerce,10,"['fractional investment', 'tangible assets', '...",1,NaN,NaN,NaN,NaN,simventure-gmbh,1,NaN,NaN,balldesigner,1,NaN,NaN,dreampetsai,1,NaN,NaN,2016,14,9,14,NaN,NaN,9,11,['Hello Again erreicht 10 Millionen App-User:i...,1,10,1,4500000,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45,16,12,15,0.21,5,NaN,NaN,NaN,NaN

**Drop unnecassary description analysis**

In [18]:
for col in df_small.columns:
    print(col)

name
link_startupeu
link_logo
link_website
website_up
city
region
category
top_3_keywords
business_model
linkedin_global_profile
linkedin_handle
linkedin_valid
instagram_handle
instagram_valid
x_handle
x_valid
founded_year
age
total_funding_listing
headline_count
headlines
headline_financial_count
headline_funding
headline_acquisition_count
headline_bankruptcy_count
headline_non_financial_count
description_writing_score
description_market_readiness_score
description_founder_signal_score
description_word_count
description_jargon_density
description_numeric_evidence_count

In [15]:
df_small.drop(columns=[
    "clarity_score",
    "innovativeness_score",
    "sentiment_score",
    "traction_score",
    "sentence_count",
    "call_to_action_flag"
], inplace=True)

In [17]:
# 1) Define the rename mapping
rename_map = {
    "writing_score":            "description_writing_score",
    "market_readiness_score":   "description_market_readiness_score",
    "founder_signal_score":     "description_founder_signal_score",
    "word_count":               "description_word_count",
    "jargon_density":           "description_jargon_density",
    "numeric_evidence_count":   "description_numeric_evidence_count"
}

# 2) Apply the renaming
df_small.rename(columns=rename_map, inplace=True)

# 3) (Optional) Verify the change
print(df_small.columns.tolist())

['name', 'link_startupeu', 'link_logo', 'link_website', 'website_up', 'city', 'region', 'category', 'top_3_keywords', 'business_model', 'linkedin_global_profile', 'linkedin_handle', 'linkedin_valid', 'instagram_handle', 'instagram_valid', 'x_handle', 'x_valid', 'founded_year', 'age', 'total_funding_listing', 'headline_count', 'headlines', 'headline_financial_count', 'headline_funding', 'headline_acquisition_count', 'headline_bankruptcy_count', 'headline_non_financial_count', 'description_writing_score', 'description_market_readiness_score', 'description_founder_signal_score', 'description_word_count', 'description_jargon_density', 'description_numeric_evidence_count']

## Create Success Variable

### Closed Startups

In [24]:
# Define the columns you want to inspect
cols = [
    "name",
    "linkedin_valid",
    "instagram_valid",
    "x_valid",
    "total_funding_listing",
    "headline_count",
    "headline_financial_count",
    "headline_funding",
    "headline_acquisition_count",
    "headline_bankruptcy_count"
]

# Subset the bad_websites DataFrame
bad_websites = df_small[df_small["website_up"] == False]

# Display the selected columns for inspection
print(f"Entries with website_up = False: {len(bad_websites)}\n")
display(bad_websites[cols])

Entries with website_up = False: 73

                               name  linkedin_valid  instagram_valid  x_valid             total_funding_listing  headline_count  headline_financial_count  headline_funding  headline_acquisition_count  headline_bankruptcy_count
64                        Whalecard           False            False    False               Between €100K-€500K               0                         0                 0                           0                          0
82                           HeyBob           False             True    False         Between €500K-€ 1 million               0                         0                 0                           0                          0
83                          Whistle            True            False     True          No funding announced yet               2                         0                 0                           0                          0
89                   Destination360            True             True    False          No funding announced yet               0                         0                 0                           0                          0
102                    Add to Water            True            False    False               Between €100K-€500K               5                         5            500000                           0                          0
104                        And-Less            True             True    False          No funding announced yet               0                         0                 0                           0                          0
110                            nuvo           False             True     True          No funding announced yet               8                         5          77660000                           0                          0
118                           ReDev            True             True     True               Between €100K-€500K               2                         1            100000                           0                          0
122                          Datogy            True             True    False          No funding announced yet               0                         0                 0                           0                          0
129                       Pluz Care            True             True    False         Between €500K-€ 1 million               4                         3                 0                           1                          1
141                           Quork           False             True    False          No funding announced yet               0                         0                 0                           0                          0
145                         exo one           False             True    False          No funding announced yet               4                         4                 0                           0                          0
146            Celeris Therapeutics           False            False     True  Between €1 million-€ 2.5 million               2                         2           4400000                           0                          0
154                         Vinitor            True             True    False          No funding announced yet               0                         0                 0                           0                          0
162                        Openlaws            True            False     True                  Between €1-€100K               0                         0                 0                           0                          0
169                       Klarsicht            True             True     True         Between €500K-€ 1 million               7                         3          20000000                           1                          2
176                     Dark Forest            True            False     True               Between €100K-€500K               1                         1                 0                           0                          0
187               I Style You Daily           False             True    False          No funding announced yet               0                         0                 0                           0                          0
192                          Ataleo           False             True    False         Between €500K-€ 1 million               2                         0                 0                           0                          2
193                      ArtAdvance           False             True    False          No funding announced yet               0                         0                 0                           0                          0
198                      Ada Growth           False            False    False         Between €500K-€ 1 million               6                         4                 0                           0                          0
199                  Affluens Group           False            False    False          No funding announced yet               0                         0                 0                           0                          0
202                      CrowdTiger            True             True    False          No funding announced yet               0                         0                 0                           0                          0
204                            hNow            True             True    False                  Between €1-€100K               1                         0                 0                           0                          1
207                           mlxar           False             True    False                  Between €1-€100K               0                         0                 0                           0                          0
209               OPEN social audio            True            False    False          No funding announced yet               1                         0                 0                           0                          0
212                       BugBattle           False            False    False          No funding announced yet               1                         0                 0                           0                          0
222             Blue Monday Project           False             True    False          No funding announced yet               0                         0                 0                           0                          0
227                   Similio Media            True             True     True          No funding announced yet               3                         0                 0                           0                          0
229                         Guestia           False             True     True          No funding announced yet               1                         1                 0                           1                          0
235                       Venturify           False            False    False          No funding announced yet               0                         0                 0                           0                          0
238                       Taxtastic           False             True     True          No funding announced yet               0                         0                 0                           0                          0
240                           Splex            True             True    False          No funding announced yet               0                         0                 0                           0                          0
245                Rare Earth Games            True             True    False          No funding announced yet               3                         3                 0                           2                          0
255               Jongerius ecoduna           False             True    False          No funding announced yet               6                         0                 0                           0                          0
258                         NumberX            True             True    False          No funding announced yet               2                         2                 0                           0                          0
259                 Hygiene Austria            True            False    False          No funding announced yet               3                         0                 0                           0                          1
271                          Brusli           False             True    False  Between €1 million-€ 2.5 million               0                         0                 0                           0                          0
291                     DOMA.market           False             True    False  Between €1 million-€ 2.5 million               0                         0                 0                           0                          0
294                   TALENT & MORE           False            False     True          No funding announced yet               0                         0                 0                           0                          0
302                          Wiffme           False            False    False          No funding announced yet               1                         0                 0                           0                          0
312                    Secondra.com           False            False    False                  Between €1-€100K               3                         0                 0                           0                          0
318                          Shoepy           False            False    False          No funding announced yet               2                         2                 0                           1                          0
323                            TMIA           False            False     True          No funding announced yet               1                         1            600000                           0                          0
329                          AVISIO            True             True    False          No funding announced yet               2                         0                 0                           0                          2
331                      Coinpanion            True            False     True  Between €1 million-€ 2.5 million               5                         4           1800000                           3                          0
332                        Pixofarm           False             True     True          No funding announced yet               2                         1           1000000                           0                          1
342                            Uloo            True             True     True          No funding announced yet               0                         0                 0                           0                          0
347                       Teamstack           False            False     True          No funding announced yet               1                         1            100000                           0                          0
356                       Rosterize            True            False    False          No funding announced yet               0                         0                 0                           0                          0
357                      Rebel Meat           False            False     True          No funding announced yet               8                         5                 0                           4                          0
365  NEXTPART Security Intelligence           False            False    False          No funding announced yet               2                         0                 0                           0                          0
390                          AISEMO            True            False    False          No funding announced yet               1                         0                 0                           0                          1
393                   Liquidary.com           False            False     True          No funding announced yet               1                         0                 0                           0                          0
395                      i4SEE TECH           False            False    False          No funding announced yet               1                         0                 0                           0                          0
400                           Fauna           False            False     True          No funding announced yet               1                         1                 0                           0                          0
401           Pow Wow Entertainment            True             True     True          No funding announced yet               1                         0                 0                           0                          0
402                     Pregenerate            True             True     True               Between €100K-€500K               1                         0                 0                           0                          1
407                  SignD Identity           False            False    False  Between €1 million-€ 2.5 million               5                         0                 0                           0                          1
410                        CNQRCLUB           False            False    False          No funding announced yet               0                         0                 0                           0                          0
419                           Yolly            True            False     True          No funding announced yet               0                         0                 0                           0                          0
423                         Trality            True             True     True  Between €1 million-€ 2.5 million               7                         4            100000                           0                          2
425                 B.A.M Ticketing            True             True     True               Between €100K-€500K               0                         0                 0                           0                          0
427      Automated Software Testing            True            False    False         Between €500K-€ 1 million               1                         0                 0                           0                          0
429         3P-Pitch Partner Pandur           False            False     True          No funding announced yet               3                         0                 0                           0                          0
431                FetoLife Science           False            False    False  Between €1 million-€ 2.5 million               2                         0                 0                           0                          0
434                         Progeny           False             True     True          No funding announced yet               3                         0                 0                           0                          0
435                          Xaleon           False             True     True          No funding announced yet               8                         5                 0                           5                          0
438            Generation55plus.net           False            False    False          No funding announced yet               1                         0                 0                           0                          0
446                         Fintune           False             True    False         Between €500K-€ 1 million               1                         0                 0                           0                          0
461                         Velonto           False             True    False          No funding announced yet               3                         2                 0                           1                          0
474                      dinster.at           False             True    False          No funding announced yet               1                         0                 0                           0                          0
507                         Ubiq.ai           False            False    False         Between €500K-€ 1 million               2                         1           1000000                           0                          0

**Create Status column and adjust status based on website_up = False:**

website down = inactive   
website down + bankrupcy headline = bankrupt

In [25]:
import numpy as np

# 1) Initialize the new column with NaN
df_small["status"] = np.nan

# 2) Build masks
mask_down    = df_small["website_up"] == False
mask_bankrupt = mask_down & (df_small["headline_bankruptcy_count"] >= 1)

# 3) Assign “bankrupt” where site is down AND at least one bankruptcy headline
df_small.loc[mask_bankrupt, "status"] = "bankrupt"

# 4) Assign “inactive” where site is down but no bankruptcy headlines
df_small.loc[mask_down & ~mask_bankrupt, "status"] = "inactive"

# 5) (Optional) Verify
print(df_small[["name","website_up","headline_bankruptcy_count","status"]].head(10))

                   name  website_up  headline_bankruptcy_count status
0                Avdain        True                          0    NaN
1          Popper Power        True                          4    NaN
2             Setter AI        True                          0    NaN
3          SurveySensum        True                          0    NaN
4                Artypa        True                          0    NaN
5              Podpally        True                          0    NaN
6       Wedding Capsule        True                          0    NaN
7  Hyrox Training Plans        True                          0    NaN
8                506.ai        True                          0    NaN
9         Get Worksheet        True                          0    NaN

C:\Users\mihim\AppData\Local\Temp\ipykernel_24396\684676529.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'bankrupt' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_small.loc[mask_bankrupt, "status"] = "bankrupt"

**Active / No funding Startups**

website_up = True  
total_funding_listing = No funding announced yet  
headline_funding = 0

In [27]:
# 1) Filter for the target cohort
no_fund = df_small[
    (df_small["website_up"] == True)
    & (df_small["total_funding_listing"] == "No funding announced yet")
    & (df_small["headline_funding"] == 0)
].copy()

In [31]:
# Define the columns to display
display_cols = [
    "name",
    "link_website",
    "linkedin_valid",
    "instagram_valid",
    "x_valid",
    "headline_count",
    "headline_acquisition_count",
    "headline_bankruptcy_count",
    "headline_non_financial_count",
    "status"
]

# Show the filtered no_fund DataFrame with just those columns
from IPython.display import display
display(no_fund[display_cols].head())

              name        link_website  linkedin_valid  instagram_valid  x_valid  headline_count  headline_acquisition_count  headline_bankruptcy_count  headline_non_financial_count status
0           Avdain          avdain.com           False            False    False               0                           0                          0                             0    NaN
3     SurveySensum    surveysensum.com            True             True     True               0                           0                          0                             0    NaN
4           Artypa          artypa.com           False             True    False               0                           0                          0                             0    NaN
5         Podpally        podpally.com           False            False    False               0                           0                          0                             0    NaN
6  Wedding Capsule  weddingcapsule.net           False            False     True               0                           0                          0                             0    NaN

In [32]:
# 1) Build mask for the “no funding” condition
mask_no_fund = (
    (df_small["website_up"] == True) &
    (df_small["total_funding_listing"] == "No funding announced yet") &
    (df_small["headline_funding"] == 0)
)

# 2) Assign “no_funding” to the status column for those rows
df_small.loc[mask_no_fund, "status"] = "no_funding"

# 3) (Optional) Verify the assignments
print(df_small.loc[mask_no_fund, ["name", "status"]].head())

              name      status
0           Avdain  no_funding
3     SurveySensum  no_funding
4           Artypa  no_funding
5         Podpally  no_funding
6  Wedding Capsule  no_funding

**Definite Funding**

In [35]:
# 1) Filter for startups with site up, listing funding ≠ “No funding announced yet”, and at least one headline funding event
mask_funded = (
    (df_small["website_up"] == True) &
    (df_small["total_funding_listing"] != "No funding announced yet") &
    (df_small["headline_funding"] != 0)
)
funded = df_small.loc[mask_funded].copy()

In [39]:
display_cols = [
    "name",
    "link_website",
    "total_funding_listing",
    "headline_funding",
    "headline_count",
    "headline_acquisition_count",
    "headline_bankruptcy_count",
    "headline_non_financial_count",
    "linkedin_valid",
    "instagram_valid",
    "x_valid"
]

display(funded[display_cols].reset_index(drop=True).head())

            name   link_website             total_funding_listing  headline_funding  headline_count  headline_acquisition_count  headline_bankruptcy_count  headline_non_financial_count  linkedin_valid  instagram_valid  x_valid
0     SimVenture  simventure.at  Between €1 million-€ 2.5 million           1000000               2                           0                          0                             1            True             True     True
1      Seven Bel   sevenbel.com         Between €500K-€ 1 million            500000               2                           0                          0                             1            True             True     True
2  infrared.city  infrared.city  Between €1 million-€ 2.5 million           1000000               2                           0                          0                             1            True             True     True
3         refinq     refinq.com         Between €500K-€ 1 million            500000               2                           0                          0                             0            True            False    False
4        myAcker    myacker.com               Between €100K-€500K          20000000               6                           0                          0                             3            True             True    False

In [40]:
# 1) Build the mask for “funding” condition
mask_funding = (
    (df_small["website_up"] == True) &
    (df_small["total_funding_listing"] != "No funding announced yet") &
    (df_small["headline_funding"] != 0)
)

# 2) Assign “funding” to the status column for those rows
df_small.loc[mask_funding, "status"] = "funding"

# 3) (Optional) Verify the assignments
print(df_small.loc[mask_funding, ["name", "status"]].head())

             name   status
27     SimVenture  funding
28      Seven Bel  funding
36  infrared.city  funding
47         refinq  funding
49        myAcker  funding

**Addition**

In [45]:
mask_funded_2 = (
    (df_small["website_up"] == True) &
    (df_small["total_funding_listing"] == "No funding announced yet") &
    (df_small["headline_funding"] != 0)
)
funded_2 = df_small.loc[mask_funded_2].copy()

display(funded_2[display_cols].reset_index(drop=True))

                 name          link_website     total_funding_listing  headline_funding  headline_count  headline_acquisition_count  headline_bankruptcy_count  headline_non_financial_count  linkedin_valid  instagram_valid  x_valid
0               DAIKI                dai.ki  No funding announced yet           1500000               3                           0                          0                             1            True            False    False
1           Glasskube          glasskube.eu  No funding announced yet            462700               3                           0                          0                             0            True            False     True
2               Ohana          tryohana.com  No funding announced yet        1200000000               5                           0                          0                             2            True             True     True
3            Metaloop           metaloop.eu  No funding announced yet          16000000              10                           0                          0                             5            True             True    False
4              HeldYn            heldyn.com  No funding announced yet            600000              10                           0                          0                             0            True             True    False
5                fynk              fynk.com  No funding announced yet           4500000               6                           0                          0                             1            True             True     True
6        HELLO INSIDE       helloinside.com  No funding announced yet           1650000               5                           1                          0                             1            True             True    False
7           Xperience      xperience.social  No funding announced yet            600000               4                           0                          0                             1            True             True     True
8             VIRIDAD            viridad.eu  No funding announced yet           1000000               1                           0                          0                             0            True            False     True
9               mjuks             mjuks.com  No funding announced yet            600000               5                           0                          0                             3            True             True    False
10      Luminous Labs       luminousred.com  No funding announced yet            600000               4                           0                          0                             3           False             True     True
11        imd BIOTECH        imdbiotech.com  No funding announced yet            400000               5                           0                          0                             4            True            False    False
12           Econutri          econutri.com  No funding announced yet            100000               3                           0                          0                             1            True             True     True
13            Fermify           fermify.org  No funding announced yet           6000000               6                           0                          0                             0            True            False    False
14         Revo Foods        revo-foods.com  No funding announced yet           2200000               9                           0                          0                             3            True             True     True
15      blackshark.ai         blackshark.ai  No funding announced yet          45480000               8                           1                          0                             3            True            False     True
16              Seasy              seasy.at  No funding announced yet            300000               7                           0                          0                             2            True             True    False
17           enspired  enspired-trading.com  No funding announced yet          25750000               9                           0                          0                             5            True             True    False
18          SAN Group         san-group.com  No funding announced yet          45000000               5                           0                          0                             2            True             True    False
19           Proxygen          proxygen.com  No funding announced yet        3000000000               3                           0                          0                             0            True            False     True
20             Mazing          mazingxr.com  No funding announced yet            100000               1                           0                          0                             0            True             True    False
21          Kickscale         kickscale.com  No funding announced yet           1000000               8                           0                          0                             3            True             True     True
22        Findustrial        findustrial.io  No funding announced yet           1000000               5                           0                          0                             1            True             True    False
23    Danube Dynamics    danube-dynamics.at  No funding announced yet            600000               9                           0                          0                             2            True             True    False
24     Carbon Cleanup    carbon-cleanup.com  No funding announced yet            700000               5                           0                          0                             0            True             True     True
25             myReha             myreha.ai  No funding announced yet           8800000               6                           0                          0                             1           False            False    False
26              Inoqo             inoqo.com  No funding announced yet           2000000               7                           0                          0                             3            True             True    False
27             Circly             circly.at  No funding announced yet           6000000               9                           0                          0                             2            True            False    False
28     World Data Lab          worlddata.io  No funding announced yet           1000000               8                           0                          0                             7            True             True     True
29         MADiscover        madiscover.com  No funding announced yet            350000               1                           0                          0                             0            True            False    False
30  e.battery systems  e-batterysystems.com  No funding announced yet          11000000               8                           0                          0                             2            True             True    False
31         Joinpoints        joinpoints.net  No funding announced yet            600000               3                           0                          0                             0            True             True    False
32               XUND               xund.ai  No funding announced yet           6000000               8                           0                          0                             3            True             True     True
33          hi.health           hihealth.de  No funding announced yet           6000000               8                           2                          0                             3           False            False     True
34              CASHY              cashy.at  No funding announced yet          10300000               8                           0                          0                             1           False             True    False
35               WisR          growwisr.com  No funding announced yet            250000               7                           0                          2                             2           False             True    False
36      APEX Ventures         apex.ventures  No funding announced yet          10000000               2                           0                          0                             1            True             True     True

In [46]:
# Build the additional mask for “funding” even if the listing says “No funding announced yet”
mask_funding_override = (
    (df_small["website_up"] == True) &
    (df_small["total_funding_listing"] == "No funding announced yet") &
    (df_small["headline_funding"] != 0)
)

# Assign “funding” to those rows as well
df_small.loc[mask_funding_override, "status"] = "funding"

# Optional: verify the change
print(df_small.loc[mask_funding_override, ["name", "total_funding_listing", "headline_funding", "status"]].head())

          name     total_funding_listing  headline_funding   status
11       DAIKI  No funding announced yet           1500000  funding
94   Glasskube  No funding announced yet            462700  funding
109      Ohana  No funding announced yet        1200000000  funding
111   Metaloop  No funding announced yet          16000000  funding
114     HeldYn  No funding announced yet            600000  funding

## Unclear Funding situation

In [51]:
display_cols = [
    "name",
    "link_website",
    "total_funding_listing",
    "headline_funding",
    "headline_count",
    "headline_acquisition_count",
    "headline_bankruptcy_count",
    "headline_non_financial_count",
    "linkedin_valid",
    "instagram_valid",
    "x_valid",
    "status"
]

mask_funded_3 = (
    (df_small["website_up"] == True) &
    (df_small["total_funding_listing"] != "No funding announced yet") &
    (df_small["headline_funding"] == 0)
)
funded_3 = df_small.loc[mask_funded_3].copy()

display(funded_3[display_cols].reset_index(drop=True).head())

            name     link_website             total_funding_listing  headline_funding  headline_count  headline_acquisition_count  headline_bankruptcy_count  headline_non_financial_count  linkedin_valid  instagram_valid  x_valid            status
0   Popper Power  popperpower.com         Between €500K-€ 1 million                 0               4                           0                          4                             0            True             True    False  probably_funding
1      Setter AI    trysetter.com                  Between €1-€100K                 0               0                           0                          0                             0           False             True     True               NaN
2         506.ai           506.ai  Between €1 million-€ 2.5 million                 0               3                           0                          0                             3            True             True     True  probably_funding
3  Get Worksheet  getworksheet.co                  Between €1-€100K                 0               0                           0                          0                             0           False            False    False               NaN
4       Hypertxt      hypertxt.ai               Between €100K-€500K                 0               1                           0                          0                             1           False            False    False               NaN

In [50]:
# 1) Define the mask for “probably_funding”
mask_probably = (
    (df_small["website_up"] == True) &
    (df_small["total_funding_listing"] != "No funding announced yet") &
    (df_small["headline_funding"] == 0) &
    (df_small["headline_count"] >= 3)
)

# 2) Assign “probably_funding” to status for those rows
df_small.loc[mask_probably, "status"] = "probably_funding"

# 3) (Optional) Verify how many and a sample
print(f"Assigned 'probably_funding' to {mask_probably.sum()} startups")
print(df_small.loc[mask_probably, ["name", "total_funding_listing", "headline_count", "headline_funding", "status"]].head())

Assigned 'probably_funding' to 34 startups
                   name             total_funding_listing  headline_count  headline_funding            status
1          Popper Power         Between €500K-€ 1 million               4                 0  probably_funding
8                506.ai  Between €1 million-€ 2.5 million               3                 0  probably_funding
31             N Vision                 Above €25 million               4                 0  probably_funding
32           money:care                  Between €1-€100K               4                 0  probably_funding
38  Enzyan Biocatalysis                 Above €25 million               7                 0  probably_funding

In [52]:
# 1) Define the mask for “unclear”
mask_unclear = (
    (df_small["website_up"] == True) &
    (df_small["total_funding_listing"] != "No funding announced yet") &
    (df_small["headline_funding"] == 0) &
    (df_small["headline_count"] < 3)
)

# 2) Assign “unclear” to status for those rows
df_small.loc[mask_unclear, "status"] = "unclear"

# 3) (Optional) Verify how many and a quick look
print(f"Assigned 'unclear' to {mask_unclear.sum()} startups")
print(df_small.loc[mask_unclear, ["name", "headline_count", "headline_funding", "status"]].head())

Assigned 'unclear' to 76 startups
              name  headline_count  headline_funding   status
2        Setter AI               0                 0  unclear
9    Get Worksheet               0                 0  unclear
15        Hypertxt               1                 0  unclear
17           digna               0                 0  unclear
20  Permar AI Inc.               0                 0  unclear

In [53]:
# Count the number of startups in each status category
status_counts = df_small["status"].value_counts(dropna=False)
print(status_counts)

status
no_funding          215
funding             111
unclear              76
inactive             62
probably_funding     34
bankrupt             11
Name: count, dtype: int64

In [ ]:
# Final version
df_small.to_csv("./data/eustartup_listings_final.csv", index=False)

## Create Version to work with 
exclude:
- unclear
- probably_funding
- bankrupt

In [55]:
# Define statuses to exclude
exclude_statuses = ["unclear", "probably_funding", "bankrupt"]

# Create a new DataFrame excluding those statuses
df_filtered = df_small.loc[
    ~df_small["status"].isin(exclude_statuses)
].reset_index(drop=True)

# Optional: inspect counts
print("Original:", len(df_small), "Filtered:", len(df_filtered))

Original: 509 Filtered: 388

In [57]:
df_filtered.to_csv("./data/startup_df.csv", index=False)